#Баринов Дмитрий ББСО-01-20 задание 2
"""Задание 2.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WfHHJIklew5H9OQdCbfCoqzcjp4TU76g
"""

import numpy 
from scipy.linalg import svd

matrix = numpy.array(((1,2,3,4,5), (5,1,2,3,4), (4,5,1,2,3), (3,4,5,1,2), (2,3,4,5,1)))
for i in matrix: 
  print(i)

U, s, V = svd(matrix)

print("U: ")
for i in U: 
  print(i)

print("s: ")
print(s)

print("V: ")
for i in V: 
  print(i)

U = U[:2]
V = V[:2] #redused size

print("U: ")
for i in U: 
  print(i)

print("V: ")
for i in V: 
  print(i)

no_name = matrix[1]
print("no_name: ", no_name)

low = numpy.dot(no_name, V.transpose())
print("Reduced dimension:", low)

inversed_transformation = numpy.dot(low, V)
print("Vector of ratings:", inversed_transformation)

print("Index best rated film:", numpy.argmax(inversed_transformation))

U, s, V = svd(matrix)
U = U[:3]
V = V[:3]
new = numpy.array((5,5,5,0,5))
print("new user rates:", new)
lowdim = numpy.dot(new, V.transpose())
print("Reduced dimension new:", lowdim)
inversed_transformation = numpy.dot(lowdim, V) 
print("Vector of ratings new:", inversed_transformation)

maximum = 0
for i in range(len(new)): 
  if new[i] == 0 and inversed_transformation[i] > maximum:
    maximum = inversed_transformation[i]
    maximum_i = i 
print("Index of the movie with the highest rating not viewed by a new user:", maximum_i)
